### ISSUE TITLE
Empty struct warning?

### ISSUE THREAD

**Issue by anpete** [JetBrains/kotlin-native#3552] opened 2019-11-05 19:15 UTC
Native compiler is generating the following warning:
```
/var/folders/5_/ps5dhtf93d3gykbtr9stv7qh0000gn/T/konan_temp2849286529694188944/api.cpp:1033:15: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
              struct {
              ^
```
Can I ignore this? If so, how can I suppress it?

**Comment by olonho** [comment] 2019-11-05 19:33
As clang suggests, use `-Wno-extern-c-compat`. This warning is harmless.

**Comment by anpete** [comment] 2019-11-05 20:47
Thanks. I'm having trouble figuring out how to specify that using the Gradle multiplatform plugin. Any help would be much appreciated.

**Comment by artdfel** [comment] 2019-11-06 11:36
Hello @anpete! Can you please share at which stage of the project build you're facing this warning?

**Comment by anpete** [comment] 2019-11-06 17:46
The warning is produced when executing any of the "link_X_" gradle tasks that are provided via the kotlin multiplatform plugin. The warnings started appearing after I made several types and global functions internal. Could it be related to kotlin files that only have internal declarations?

**Comment by artdfel** [comment] 2019-11-07 09:55
Please try to add the flag to the `linkerOpts` property of your binary. Example of its usage one can find [in this doc](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#using-kotlinnative-targets)

**Comment by olonho** [comment] 2019-11-08 06:11
`compilerOpts`, not linker one.

**Comment by anpete** [comment] 2019-11-11 19:23
Assuming you mean `freeCompilerArgs`?

I tried this:
```
mingwX64("mingw") {
        binaries {
            sharedLib {
                baseName = "mylib"
                freeCompilerArgs = mutableListOf("-Wno-extern-c-compat")
            }
        }
    }
```
And got this:
```
e: Invalid argument: -Wno-extern-c-compat
```

**Comment by artdfel** [comment] 2019-11-28 13:42
Hello again, @anpete, and sorry for such a long period of silence!
Finally, we managed to find the root cause of this warning. It has to be fixed in the compiler, so nothing can be done from your side. 
Also, I got to mention that this issue should not cause any problems(except the fact that it is quietly annoying😅). So, please don't 
worry about it, and wait for an update in this thread.

**Comment by anpete** [comment] 2019-12-02 21:04
OK, thanks!

**Comment by vvlevchenko** [comment] 2021-04-08 14:52
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of [KT-42796 [Reverse C Interop] Package with no public methods generate empty struct in the header, leading to an error](https://youtrack.jetbrains.com/issue/KT-42796)

**Closed by vvlevchenko** 2021-04-08 14:52 UTC
Labels: bug
