### ISSUE TITLE
Changing name for Objc methods

### ISSUE THREAD

**Issue by nvlizlo** [JetBrains/kotlin-native#3516] opened 2019-10-29 13:24 UTC
Hi!
In kotlin multiplatform I have the following code:
`fun withUserId(userId: String) = applySelf { this.userId = userId }` 

And it's converted in Objective-C like that:
`- (MyClass *)withUserIdUserId:(NSString *)userId __attribute__((swift_name("withUserId(userId:)")));
`

And when I call the method, my method name is doubled:

`[user withUserIdUserId:@"testId"]`

How can I omit these doubling? As I know, kotlin have `@JsName` for Javascript method names, does it have similar for Objective-C methods?

Thanks,
Nazariy

**Comment by artdfel** [comment] 2019-10-30 10:43
Hello!
Can you please share a few more complex example of the Kotlin code you're using?

**Comment by kylebrock** [comment] 2019-10-30 23:47
I would love to be able to override the obj-c naming with an annotation.

**Comment by TomCarton** [comment] 2020-04-10 04:11
Hello!

Similar need on my side, as I often have the swift names prefixed with the file name.
For instance:
  `fun print()` in Common.kt
  becomes `swift_name("CommonKt_print")`

And I would also love to have access to an annotation to instrument the name or even the prefix in files that happen to end up with such weird things...

Thank you!

**Comment by ELOVSKIY** [comment] 2021-04-28 07:19
Hello!

The problem is still relevant today.

**Comment by libill** [comment] 2021-07-28 08:27
why ? how to fix it?

**Comment by SvyatoslavScherbina** [comment] 2021-07-29 13:25
No solution at the moment.

**Comment by SvyatoslavScherbina** [comment] 2021-08-04 14:15
Moved to https://youtrack.jetbrains.com/issue/KT-48076, closing.

**Closed by SvyatoslavScherbina** 2021-08-04 14:15 UTC
