### ISSUE TITLE
No way to determine exe directory

### ISSUE THREAD

**Issue by zero9178** [JetBrains/kotlin-native#1967] opened 2018-08-29 15:28 UTC
In languages like C and C++ the directory where the exe lies is usually sent as the very first argument on the command line. Currently kotlin native has no way to get this information in a similar cross platform way without resorting to the included platform specific C APIs. This is a problem when making applications that should be adressable from the console through the system path and need to do File IO.

**Comment by zero9178** [comment] 2018-08-29 16:43
Would it be possible from a function in the stdlib? That wouldn't break compatibility

**Comment by r4zzz4k** [comment] 2018-08-31 16:15
This looks like a duplicate of #555, though there isn't much info there too.

**Comment by mikehearn** [comment] 2018-09-23 19:59
See the code here for how to do this:

https://github.com/mikehearn/graviton-browser/tree/master/bootstrap/src/main/kotlin

**Comment by olonho** [comment] 2019-04-16 16:45
There are libraries doing that, i,e. `SDL_GetBasePath` in SDL. Unlikely will be supported in base Kotlin/Native.

**Closed by olonho** 2019-04-16 16:45 UTC
