### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by astrokin** [JetBrains/kotlin-native#3652] opened 2019-12-09 20:36 UTC
The app references non-public selectors in: `alternatives`, `arrival`, `cities`, `companion`, `countries`, `currency`, `departure`, `fatal`, `info`, `initWithCode:`, `initWithDate:`, `none`, `setStorefront:`, `total`, `trace`, `transform:`, `warn`.

**Comment by SvyatoslavScherbina** [comment] 2019-12-10 07:33
Hello. Could you provide more details?

Is this warning or error?
Do you have these methods in your Kotlin framework's header file?
Is it the first submission of this app?

**Comment by astrokin** [comment] 2019-12-10 07:43
@SvyatoslavScherbina it's `binary reject` from apple after upload it to test flight. all these name (selectors) are exists in Kotlin framework's header file. It's first submission.

**Comment by SvyatoslavScherbina** [comment] 2019-12-10 07:47
Which Kotlin version do you use?

**Comment by astrokin** [comment] 2019-12-10 07:58
> Which Kotlin version do you use?

1.3.50

**Comment by olonho** [comment] 2019-12-11 05:40
Could you share the binary and the way how it was produced?

**Comment by astrokin** [comment] 2019-12-12 21:54
linking you track issue: https://youtrack.jetbrains.com/issue/KT-35453

**Comment by astrokin** [comment] 2019-12-12 21:55
Apple reject my binary created with Kotlin Multi Platform with ITMS-90338: Non-public API usage - The app references non-public selectors in app-ios: brandId, cities, companion, countries, currency, departure, fatal, info, initWithCode:, initWithDate:, none, setStorefront:, total, trace, transform:, warn. Then I've figured out that ONLY `initWithDate` make sense and leads to reject. All other selectors above do not affect binary status and builds are able to processed on Apple side without change these properties.

**Comment by SvyatoslavScherbina** [comment] 2019-12-18 17:28
This code actually gets successfully processed on Apple side for me.
So the issue must be caused by something specific in your project or account.
That's why we can't proceed with investigating the issue without exact reproducer.

**Comment by SvyatoslavScherbina** [comment] 2019-12-18 17:28
> linking you track issue: https://youtrack.jetbrains.com/issue/KT-35453

Closing this issue as duplicate then.

**Closed by SvyatoslavScherbina** 2019-12-18 17:28 UTC

**Comment by SvyatoslavScherbina** [comment] 2019-12-31 13:36
Fix will be delivered with 1.3.70 (including next EAP).
