### ISSUE TITLE
Some code could build in `kotlin-common` won't build for kotlin-native

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1592] opened 2018-05-15 00:27 UTC
This is the code:

```kotlin
            inner@ do{
                found = str.findAnyOf(inquotes, index + 1)
                when(found?.second){
                    "\"" -> {index = found.first+1; break@inner}
                    "\\" -> index = found.first+1
                }
            }while (found != null)
```

The error is:

```bash
/nz/salect/objJSONCommon/objjson.kt:16:43: error: only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Pair<Int, String>?
                    "\"" -> {index = found.first+1; break@inner}
                                          ^
```

No errors for both `jvm` and `common`

When we run the `when` block with this condition:  `found?.second`, shouldn't it just eliminate the possibility of `found` been null? Or I miss something here?

**Comment by gildor** [comment] 2018-05-15 02:32
Looks like a problem of smart cast of K/N. Maybe for now make sense just use workaround with early return:
```found = str.findAnyOf(inquotes, index + 1) ?: break@inner```

**Comment by olonho** [comment] 2018-05-15 07:08
For me following snippet compiles with the current master:
```fun main(args: Array<String>) {
   val str = "ss"
   val inquotes = listOf("'")
   var index = 0
   var found: Pair<Int, String>?
   inner@ do{
                found = str.findAnyOf(inquotes, index + 1)
                when(found?.second){
                    "\"" -> {index = found.first+1; break@inner}
                    "\\" -> index = found.first+1
                }
            } while (found != null)
}
```
COuld you please provide exact snippet, and check the behavior of the current master.

**Comment by dsavvinov** [comment] 2018-05-15 08:35
Could you also please check which `-language-version` you're using when compiling to K/N? Such smartcasts are possible only since Kotlin 1.1

**Comment by Albert-Gao** [comment] 2018-05-15 08:38
@dsavvinov I use `1.2.41`

@olonho That's interesting. Will try it tomorrow when I back to work. I noticed there is a `0.8-dev-1973 ` on bintray, can I use this one instead of `Master` to reduce the building time :D

**Comment by olonho** [comment] 2018-05-16 21:16
@Albert-Gao any news on that?

**Comment by Albert-Gao** [comment] 2018-05-17 00:40
@olonho Sorry for the wait, just tried `0.8-dev-2045`

The result is the same:

```bash
> Task :platforms:ios:compileKonanSharediOSIos_arm64 FAILED
/Users/albertgao/codes/work/kmoblib/common/main/nz/salect/objJSONCommon/objjson.kt:16:43: error: only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Pair<Int, String>?
                    "\"" -> {index = found.first+1; break@inner}
                                          ^
/Users/albertgao/codes/work/kmoblib/common/main/nz/salect/objJSONCommon/objjson.kt:17:42: error: only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Pair<Int, String>?
                    "\\" -> index = found.first+1
                                         ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platforms:ios:compileKonanSharediOSIos_arm64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Comment by Albert-Gao** [comment] 2018-05-17 00:54
Share something new:

The previous is not a blocker. Because I add add `!!` there to avoid it. Even though that is not what I want to do. :D

But now there is another problem.

```bash
.... Omit many many lines like below
!3413 = distinct !DISubprogram(scope: !45, file: !45, type: !387, isLocal: false, isDefinition: true, isOptimized: false, unit: !44, variables: !68)
!3414 = !DILocation(line: 9, column: 9, scope: !3413)
!3415 = !DILocation(line: 0, scope: !3413)
error: compilation failed: Invalid module

 * Source files: api.kt, OrderStatus.kt, business.kt, setting.kt, Favourite.kt, Interfaces.kt, Menu.kt, MenuAndOrder.kt, Order.kt, AlreadyMemberRequest.kt, AuthService.kt, MenuService.kt, Utils.kt, FavouriteStore.kt, JsonStore.kt, MenuStore.kt, OrderStore.kt, UserPreference.kt, AuthHelper.kt, Utils.kt, HttpResponse.kt, http.kt, File.kt, Settings.kt, DeviceId.kt, utils.kt, objjson.kt, http.kt, utils.kt, File.kt, Settings.kt, DeviceId.kt, utils.kt
 * Compiler version info: Konan: 0.8-dev-2045 / Kotlin: 1.2.60
 * Output kind: FRAMEWORK

exception: java.lang.Error: Invalid module
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule(IrToBitcode.kt:147)
	at org.jetbrains.kotlin.backend.konan.llvm.IrToBitcodeKt.verifyModule$default(IrToBitcode.kt:138)
	at org.jetbrains.kotlin.backend.konan.Context.verifyBitCode(Context.kt:333)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt:101)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$4.invoke(KonanDriver.kt)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
	at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:90)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:75)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:42)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:95)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:69)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:37)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:168)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:159)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:197)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:188)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:34)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:29)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:190)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:202)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)


> Task :platforms:ios:compileKonanKIos_arm64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platforms:ios:compileKonanKIos_arm64'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
2 actionable tasks: 2 executed
12:49:24: Task execution finished 'build'.
```

It seems one of my module is not passing the compiler. Even though they can all be built for android without problem. I swear to god that I only use API from `kotlin-stdlib-common` in `common`, and don't throw exception in `common`, and don't use `generic` in `common`, and current `platforms:ios` is just fake `actual` implementation which just return primitive value.

I just want to assure that I didn't write anything that KN not like. Because I am about to start the iOS app pretty soon.

**Comment by olonho** [comment] 2018-05-18 14:30
Could you please provide tarball or github repo with code to reproduce this issue?

**Comment by Albert-Gao** [comment] 2018-05-18 23:36
@olonho Of course, I created a private repo, and add you already.
https://github.com/Albert-Gao/kn-ios-issue

**Comment by kpgalligan** [comment] 2018-05-20 19:03
I also just ran into "exception: java.lang.Error: Invalid module". Would love an update if one appears. I'm going to start chopping down my build to see if I can reduce it to a root cause.

**Comment by kpgalligan** [comment] 2018-05-21 00:10
I don't know if our issues will be the same root cause, but I cut down my build to fail on a pretty narrow piece of code and posted a new issue here: https://github.com/JetBrains/kotlin-native/issues/1613

**Comment by SvyatoslavScherbina** [comment] 2020-09-29 08:03
Closing as obsolete. Feel free to open a new issue if you still encounter the problem: https://kotl.in/issue.

**Closed by SvyatoslavScherbina** 2020-09-29 08:03 UTC
