### ISSUE TITLE
error: unknown type name 'libtestlib_kref_kotlin_IntArray

### ISSUE THREAD

**Issue by algidrus** [JetBrains/kotlin-native#3890] opened 2020-02-19 19:59 UTC
I've tried to build static/dynamic libs for iOS/Android, but "unknown type name 'libtestlib_kref_kotlin_IntArray" error occurs. 
If I build an executable file for MacOS it compiles and works fine without any errors.
How can I treat it?

OS: MacOS, kotlin 1.3.61

Full code of my sample:
//******************************************
package test

import kotlin.text.*
import kotlin.native.concurrent.*

fun findSum(br: ByteArray): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

fun findSum(br: UByteArray): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

fun findSum(br: UIntArray): Double {
    var sum: Double = 0.0
    for (i in 0..br.lastIndex) {
        sum+=br[i].toDouble()
    }
    return sum
}

@kotlin.ExperimentalStdlibApi
fun main(args: Array<String>)
{
    var sum = 0.0
    val arr_b = byteArrayOf(10.toByte(),
                          20.toByte(),
                          30.toByte(),
                          40.toByte(),
                          50.toByte(),
                          60.toByte(),
                          70.toByte(),
                          80.toByte(),
                          90.toByte())

    sum = findSum(arr_b)
    println("Sum = $sum")

    val arr_ub = ubyteArrayOf(10.toUByte(),
                          20.toUByte(),
                          30.toUByte(),
                          40.toUByte(),
                          50.toUByte(),
                          60.toUByte(),
                          70.toUByte(),
                          80.toUByte(),
                          90.toUByte())

    sum = findSum(arr_ub)
    println("Sum = $sum")

    val arr_ui = uintArrayOf(10.toUInt(),
                          20.toUInt(),
                          30.toUInt(),
                          40.toUInt(),
                          50.toUInt(),
                          60.toUInt(),
                          70.toUInt(),
                          80.toUInt(),
                          90.toUInt())

    sum = findSum(arr_ui)
    println("Sum = $sum")
}

**Comment by artdfel** [comment] 2020-02-20 12:53
Hello, @algidrus! Thank you for the report, seems like this is a bug.
The problem here is that, for some reason, UIntArray presence in your case did not lead to an appropriate typedef declaration in the produced library header. This can be reproduced with any primitive unsigned-type array. For signed-type ones, everything works correctly - even in your case, this is the reason why only IntArray failed - because of the first function, `libtestlib_kref_kotlin_ByteArray` typedef was generated correctly. 
To workaround this issue, I would recommend exposing all primitive type arrays explicitly - for example, just add a top-level `val regIntArray = intArrayof()`. 
And this is working correctly for Mac because of executables have no headers. If you'll try to build a library, it will fail the same way, I checked 🙂.

**Comment by algidrus** [comment] 2020-02-20 17:55
Thanks a lot) 
I hope it will be fixed in the next version ;)

**Comment by artdfel** [comment] 2020-05-21 13:31
YouTrack ticket on this issue's causes: https://youtrack.jetbrains.com/issue/KT-36878.

**Comment by SvyatoslavScherbina** [comment] 2020-08-13 14:38
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-36878

**Closed by SvyatoslavScherbina** 2020-08-13 14:38 UTC
