### ISSUE TITLE
Does Support Android x86 / x86_64 probably ??

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#3301] opened 2019-09-02 02:52 UTC
I Create Project.

In android, I need build .so file, so use androidNativeArm64, but I need x86 / x86_64 also,  

I find it is only support arm64 / arm32, 

Does K/N supports Android ndk with x86 / x86_64 probably in the next version ??

**Comment by artdfel** [comment] 2019-09-02 07:54
Duplicate of #3272, closing.

**Closed by artdfel** 2019-09-02 07:54 UTC
