### ISSUE TITLE
Swift/ObjC: inline class instances unusable in generic context

### ISSUE THREAD

**Issue by fluidsonic** [JetBrains/kotlin-native#3032] opened 2019-05-28 21:14 UTC
Kotlin:
```kotlin
inline class Something(val value: Int)
```

Swift, when an instance is used in a generic context like a `Dictionary`:
```swift
let value: Any = dictionary[…]
print(type(of: value)) // kobjcc3
print(value) // Something(value=123)

value as! Int       // doesn't work
value as! Int32     // doesn't work
value as! KotlinInt // doesn't work
value as! NSNumber  // doesn't work
```
It seems to be impossible to cast the value to anything meaningful.

As a workaround an unwrapping function can be added on the Kotlin side:
```kotlin
fun unwrap(unsafe: Any) =
	(unsafe as Something).value
```

Swift:
```swift
let value: Int32 = SomethingKt.unwrap(unsafe: dictionary[…])
```

**Comment by benasher44** [comment] 2019-05-28 22:37
Dup of #2961?

**Comment by fluidsonic** [comment] 2019-05-29 05:55
@benasher44 no, that's a different issue.
#2961 is about properly supporting inline classes in ObjC/Swift with all their type-safety, functions and properties.

This issue is about access to the wrapped value which is possible in most cases already - except for this one.

**Comment by benasher44** [comment] 2019-05-29 12:29
> This issue is about access to the wrapped value which is possible in most cases already - except for this one.

Really? My example shows the class isn’t accessible at all, including the wrapped value

**Comment by fluidsonic** [comment] 2019-05-29 12:36
I have plenty of classes which have properties or functions returning inline classes which wrap an `Int`.
They are represented directly as `Int32` in Swift.

**Comment by benasher44** [comment] 2019-05-29 15:20
Oh interesting. I just played with this some more, and it appears that an `inline class` that wraps an `Int` is exposed as an `int_32t` in Obj-C just fine, but a `String` is exposed as `id`. I'll update my ticket. Thanks!

**Comment by SvyatoslavScherbina** [comment] 2020-04-13 12:37
Closing as duplicate of https://youtrack.jetbrains.com/issue/KT-32352

**Closed by SvyatoslavScherbina** 2020-04-13 12:37 UTC
