### ISSUE TITLE
AssertionError during reinitializing the value of Lazy member

### ISSUE THREAD

**Issue by and-marsh** [JetBrains/kotlin-native#3868] opened 2020-02-14 08:12 UTC
Hello, i found an issue related to usage of `Lazy` members of frozen objects.
For example, i have MPP project with iOS native module:
```Kotlin
// SampleIos.kt
package sample

import kotlin.native.concurrent.freeze

actual class Sample {

    actual val lazyVal: String by lazy {
        throw Exception("Some exception")
    }

    init {
        this.freeze()
    }
}
```
And iOS test:
```Kotlin
// SampleTestNative.kt
package sample

import kotlin.test.Test

class SampleTestsNative {

    @Test
    fun testLazy() {

        val test = Sample()
        try {
            test.lazyVal
        } catch (e: Exception) {
            println(e)
        }

        test.lazyVal
    }
}
```
I expected lazy value to throw same exception every time when it is called:
> If the initialization of a value throws an exception, it will attempt to reinitialize the value at next access.

But instead of this i have `AssertionError` for second attempting of access

Error trace of `gradle iosTest`:
```
[ RUN      ] sample.SampleTestsNative.testLazy
kotlin.Exception: Some exception
kotlin.AssertionError: Assertion failed
Invalid connection: com.apple.coresymbolicationd
        at 0   test.kexe                           0x0000000107eacbc7 kfun:kotlin.Throwable.<init>(kotlin.String?)kotlin.Throwable + 87 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/Throwable.kt:22:37)
        at 1   test.kexe                           0x0000000107ea71f5 kfun:kotlin.Error.<init>(kotlin.String?)kotlin.Error + 85 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/Exceptions.kt:12:44)
        at 2   test.kexe                           0x0000000107ea7702 kfun:kotlin.AssertionError.<init>(kotlin.Any?)kotlin.AssertionError + 226 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/Exceptions.kt:128:41)
        at 3   test.kexe                           0x0000000107ed4066 kfun:kotlin.native.concurrent.FreezeAwareLazyImpl.<get-value>()#GENERIC + 2278 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/concurrent/Lazy.kt:28:0)
        at 4   test.kexe                           0x0000000107f86c34 kfun:sample.Sample.<get-lazyVal>()kotlin.String + 308 (/Users/and_marsh/Documents/untitled/src/iosMain/kotlin/sample/SampleIos.kt:9:0)
        at 5   test.kexe                           0x0000000107f878be kfun:sample.SampleTestsNative.testLazy() + 446 (/Users/and_marsh/Documents/untitled/src/iosTest/kotlin/sample/SampleTestsNative.kt:23:14)
        at 6   test.kexe                           0x0000000107f87d93 kfun:sample.$SampleTestsNative$test$0.$testLazy$FUNCTION_REFERENCE$2.invoke#internal + 67 (/Users/and_marsh/Documents/untitled/src/iosTest/kotlin/sample/SampleTestsNative.kt:13:5)
        at 7   test.kexe                           0x0000000107f87e09 kfun:sample.$SampleTestsNative$test$0.$testLazy$FUNCTION_REFERENCE$2.$<bridge-UNNN>invoke(#GENERIC)#internal + 89 (/Users/and_marsh/Documents/untitled/src/iosTest/kotlin/sample/SampleTestsNative.kt:13:5)
        at 8   test.kexe                           0x0000000107ef8219 kfun:kotlin.native.internal.test.BaseClassSuite.TestCase.run() + 1289 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/TestSuite.kt:85:26)
        at 9   test.kexe                           0x0000000107ef1f70 kfun:kotlin.native.internal.test.TestRunner.run#internal + 2416 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:229:0)
        at 10  test.kexe                           0x0000000107ef3112 kfun:kotlin.native.internal.test.TestRunner.runIteration#internal + 2930 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:252:0)
        at 11  test.kexe                           0x0000000107ef3a22 kfun:kotlin.native.internal.test.TestRunner.run()ValueType + 962 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:270:0)
        at 12  test.kexe                           0x0000000107ee717b kfun:kotlin.native.internal.test.testLauncherEntryPoint(kotlin.Array<kotlin.String>)ValueType + 283 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:22:53)
        at 13  test.kexe                           0x0000000107ee7037 kfun:kotlin.native.internal.test.main(kotlin.Array<kotlin.String>) + 55 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:26:17)
        at 14  test.kexe                           0x0000000107ee72cc Konan_start + 156 (/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:25:1)
        at 15  test.kexe                           0x0000000107f8fedf Init_and_run_start + 111
        at 16  libdyld.dylib                       0x00007fff5227ec25 start + 1
[  FAILED  ] sample.SampleTestsNative.testLazy (0 ms)
```
Issue https://github.com/JetBrains/kotlin-native/issues/1817 can be related to this, but i'm not sure

Kotlin version  `1.3.61`

**Comment by artdfel** [comment] 2020-02-20 14:02
Hello, @and-marsh! Thank you for the report, this bug should be fixed in the next EAP3, see (here)[https://discuss.kotlinlang.org/t/kotlin-1-3-70-early-access-preview/15876/22] some instructions on its use. Or, you can just wait for 1.3.70 release.

**Comment by and-marsh** [comment] 2020-02-25 13:34
Thank you for the answer! I'm looking forward for new release!

The issue can be closed, i suppose, but it's up to you

**Comment by artdfel** [comment] 2020-03-04 17:15
Closing as the 1.3.70 was released and I can't reproduce the error on it.

**Closed by artdfel** 2020-03-04 17:15 UTC
