### ISSUE TITLE
TypeInfo.cpp:41: runtime assert: Unknown open method

### ISSUE THREAD

**Issue by donatasbartkus** [JetBrains/kotlin-native#2638] opened 2019-02-07 10:33 UTC
My code brakes on this line running from iOs.
main/cpp/TypeInfo.cpp:41: runtime assert: Unknown open method

I think it will be more understandable if you put more information about this error (class, method name).

**Comment by olonho** [comment] 2019-02-07 10:59
This is usually a symptom of runtime bug. Could you please us with info of used Kotlin/Native and self-contained reproducer.

**Comment by donatasbartkus** [comment] 2019-02-07 14:11
kotlinVersion = '1.3.21'

Common (Example.kt):


```kotlin
package com.eld.common.eld.example

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.async
import kotlin.coroutines.CoroutineContext

open class Example(
        private val storage: Storage,
        override val coroutineContext: CoroutineContext
) : CoroutineScope {

    interface Storage {
        suspend fun findAll(): List<String>
    }

    interface IosStorage: Storage {
        override suspend fun findAll(): List<String> = findAllAsync().await()

        fun findAllAsync(): Deferred<List<String>>
    }

    suspend fun testStotrage(): List<String> {
        return storage.findAll()
    }
}

class IosExample(storage: Storage, coroutineContext: CoroutineContext): Example(storage, coroutineContext) {
    fun testStotrageAsync() = async { testStotrage() }
}
```

iOs (Example.swift)

```swift
//
//  Example.swift
//  ELD-stage
//
//  Created by Donatas Bartkus on 07/02/2019.
//  Copyright © 2019 eld. All rights reserved.
//

import Foundation
import eld_common

class exampleStorage: NSObject, ExampleIosStorage {
    private let uiDispatcher = UI()
    func findAllAsync() -> Kotlinx_coroutines_core_nativeDeferred {
        return CoroutineHelperKt.deferred(context: uiDispatcher) { () -> [String] in
            return []
        }
    }
}

class foo {
    private let uiDispatcher = UI()
    
    func bar() {
        var promise: Kotlinx_coroutines_core_nativeDeferred!
        let example = IosExample(
            storage: exampleStorage(),
            coroutineContext: uiDispatcher
        )
        promise = example.testStotrageAsync()
        promise.invokeOnCompletion(handler: { [weak self] _ in
            guard self != nil else {
                return KotlinUnit()
            }
            do {
                let result = try CoroutineHelperKt.getCompletedOrThrow(promise) as! [String]
                print(result)
            }catch {
                
            }
            return KotlinUnit()
        })
    }
}
```

calling from iOs

```swift
foo().bar()
```

**Comment by kylejbrock** [comment] 2019-02-07 15:26
I’ve experienced this using firebase performance monitoring when they swizzle the request delegates.  I had to use swift and Kotlin to work around it.

**Comment by olonho** [comment] 2019-02-07 19:05
Do you have build.gradle or even better GitHub repo with reproducer to checkout?

**Comment by SvyatoslavScherbina** [comment] 2019-02-08 07:05
Your `exampleStorage` class doesn't override `suspend fun findAll()` function.
Swift doesn't have `suspend` functions, so `findAll` method is not visible to Swift, and you can't override it in a Swift class.

**Comment by donatasbartkus** [comment] 2019-02-08 07:33
```kotlin
interface IosStorage: Storage {
        override suspend fun findAll(): List<String> = findAllAsync().await()

        fun findAllAsync(): Deferred<List<String>>
}
```
But I'm using IosStorage interface in swift and that interface override suspend fun findAll().

**Comment by SvyatoslavScherbina** [comment] 2019-02-08 07:41
Thank you for clarification.
Unfortunately, the cause is still the same.
Swift doesn't allow protocols to provide default implementations for its methods. That's why `exampleStorage` doesn't inherit one from `IosStorage`.

**Comment by olonho** [comment] 2019-04-16 16:49
So anything else left here? Could we close it?

**Comment by Thomas-Vos** [comment] 2019-05-06 12:24
@olonho Because we can't use default functions in interfaces it makes it a bit more complicated to workaround the issue with suspend functions (https://github.com/JetBrains/kotlin-native/issues/1684). This prevents me from using the suspend functions completely if I cannot provide a default implementation just like in the example by @donatasbartkus.

**Comment by SvyatoslavScherbina** [comment] 2020-04-13 14:31
https://github.com/JetBrains/kotlin-native/issues/1684 is fixed, closing this issue then.

**Closed by SvyatoslavScherbina** 2020-04-13 14:31 UTC
