### ISSUE TITLE
No K/N stack trace in released iOS framework.

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3105] opened 2019-06-24 14:26 UTC
It's very hard to locate problems.
Do you have any suggestion?

libsystem_kernel	8	___pthread_kill (in libsystem_kernel.dylib)
libsystem_c	140	_abort (in libsystem_c.dylib)
libc++abi	0	___cxa_bad_cast (in libc++abi.dylib)
libc++abi	0	default_unexpected_handler() (in libc++abi.dylib)
libobjc.A	124	_objc_terminate() (in libobjc.A.dylib)
xxxxx	332	CLSTerminateHandler() (in xxxxx)
xxxxx	HMDCPPExceptionDetector.cpp:133	hmdcrash_cpp_exception_terminate_handler() (in xxxxx)
xxxxx	312	KonanTerminateHandler() (in xxxxx)
libc++abi	16	std::__terminate(void (*)()) (in libc++abi.dylib)
libc++abi	84	std::terminate() (in libc++abi.dylib)
xxxxx	29896	missing (in xxxxx)
xxxxx	3948	missing (in xxxxx)
xxxxx	UIViewController+HMDUITracker.m:244	-[UIViewController(HMDUITracker) callOriginalFuncWtihClass:instance:selector:] (in xxxxx)
xxxxx	UIViewController+HMDUITracker.m:81	-[UIViewController(HMDUITracker) hmd_viewDidLoad] (in xxxxx)
UIKitCore	1012	-[UIViewController loadViewIfRequired] (in UIKitCore)
UIKitCore	28	-[UIViewController view] (in UIKitCore)
UIKitCore	1072	-[UINavigationController _startCustomTransition:] (in UIKitCore)
UIKitCore	708	-[UINavigationController _startDeferredTransitionIfNeeded:] (in UIKitCore)
UIKitCore	164	-[UINavigationController __viewWillLayoutSubviews] (in UIKitCore)
UIKitCore	224	-[UILayoutContainerView layoutSubviews] (in UIKitCore)
UIKitCore	1292	-[UIView(CALayerDelegate) layoutSublayersOfLayer:] (in UIKitCore)
QuartzCore	184	-[CALayer layoutSublayers] (in QuartzCore)
QuartzCore	332	CA::Layer::layout_if_needed(CA::Transaction*) (in QuartzCore)
QuartzCore	348	CA::Context::commit_transaction(CA::Transaction*) (in QuartzCore)
QuartzCore	640	CA::Transaction::commit() (in QuartzCore)
QuartzCore	92	CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) (in QuartzCore)
CoreFoundation	32	___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ (in CoreFoundation)
CoreFoundation	412	___CFRunLoopDoObservers (in CoreFoundation)
CoreFoundation	1228	___CFRunLoopRun (in CoreFoundation)
CoreFoundation	436	_CFRunLoopRunSpecific (in CoreFoundation)
GraphicsServices	104	_GSEventRunModal (in GraphicsServices)
UIKitCore	212	_UIApplicationMain (in UIKitCore)
xxxxx	main.m:14	main (in xxxxx)
libdyld	4	_start (in libdyld.dylib)

**Comment by benasher44** [comment] 2019-06-24 14:41
See #2600.

For now, we're working around this by releasing the app with a debug framework

**Comment by DTHeaven** [comment] 2019-06-24 15:10
> See #2600.
> 
> For now, we're working around this by releasing the app with a debug framework

Did you use it in official app?
How do you think about app size, performance and code security?

**Comment by benasher44** [comment] 2019-06-24 15:19
> Did you use it in official app?

Yes

> How do you think about app size, performance and code security?

We don't have quite enough code in it to be overly concerned about these things yet. So far though, we haven't been able to measure a anything concern-able. We hope release frameworks will be in a better state by then.

**Comment by DTHeaven** [comment] 2019-06-25 02:50
> > Did you use it in official app?
> 
> Yes
> 
> > How do you think about app size, performance and code security?
> 
> We don't have quite enough code in it to be overly concerned about these things yet. So far though, we haven't been able to measure a anything concern-able. We hope release frameworks will be in a better state by then.

Thanks.

**Comment by DTHeaven** [comment] 2019-06-25 02:51
@olonho @SvyatoslavScherbina 
Is there a way to hook all functions? Then we can record stack by ourselves.
Any other suggestion, or what's your plan?

**Comment by benasher44** [comment] 2019-06-25 03:07
There's a global function called setUnhandledExceptionHook for that.

**Comment by DTHeaven** [comment] 2019-06-25 03:17
> There's a global function called setUnhandledExceptionHook for that.

I mean to log every function call in KN, and send these logs to our server by UnhandledExceptionHook.

**Comment by benasher44** [comment] 2019-06-25 03:18
You can get the stack trace from the throwable there. Is that not what you're looking for?

**Comment by DTHeaven** [comment] 2019-06-25 06:46
> You can get the stack trace from the throwable there. Is that not what you're looking for?

No, there is no KN stack trace in that throwable, only Objective-C trace. Please see my first post.
Besides if the crash happens in Objective-C, UnhandledExceptionHook callback will not be invoke.

Objective-C -> KN -> Objective-C -> crash, UnhandledExceptionHook didn't work.

**Comment by benasher44** [comment] 2019-06-25 13:51
Oh I see what you mean. The issue is that symbol resolution doesn't work well yet in release frameworks. You would see Kotlin symbols in a debug framework.

**Comment by SvyatoslavScherbina** [comment] 2020-04-13 12:46
See https://kotlinlang.org/docs/reference/native/ios_symbolication.html#enable-dsym-for-release-kotlin-binaries

**Closed by SvyatoslavScherbina** 2020-04-13 12:46 UTC
