### ISSUE TITLE
package of cinterop dependency (Swift framework) not found in the iOSMain sources set

### ISSUE THREAD

**Issue by RoqueCampos** [JetBrains/kotlin-native#4543] opened 2020-11-19 17:08 UTC
I'm trying to import and use a self made Swift framework in a kotlin native shared code module, for the iOS sources set. I followed the guide to add a dependency to the iOS Sourceset: https://kotlinlang.org/docs/mobile/add-dependencies.html#without-cocoapods

The version of the kotlin gradle plugin I'm using is 1.4.10, and Android Studio 4.2 Canary 15. The project was started with the KMM template with the wizard.

The shared code module builds correctly, and in the external libraries hierarchy in android studio I can see the generated .klib libraries: 

![image](https://user-images.githubusercontent.com/6582323/99697852-66020e00-2a90-11eb-9be5-0d7cfcd8b595.png)

The content of the .knm files seems correct too:

![image](https://user-images.githubusercontent.com/6582323/99698104-aeb9c700-2a90-11eb-9903-97d75fc9f0b2.png)

But when I try to import this package in the a class of the iOSMain source set, the package is not resolved:

![image](https://user-images.githubusercontent.com/6582323/99698308-e9236400-2a90-11eb-8036-e2d5a8bcef56.png)

This is my def file:

```
language = Objective-C
modules = SlicerUtils
package = com.xxxxx.iosframeworks
```

And this is an extract of the build.gradle.kts file where the cinterop are defined:

```
    val iosFrameworkBaseDir = "${projectDir}/../../ios-frameworks"
    val slicerUtilsDir = file("$iosFrameworkBaseDir/SlicerUtils").absolutePath


    val slicerUtilsBaseFrameworkDirX64 =
        file("$slicerUtilsDir/DerivedData/SlicerUtils/Build/Products/Debug-iphonesimulator").absolutePath

    val slicerUtilsBaseFrameworkDirArm64 =
        file("$slicerUtilsDir/DerivedData/SlicerUtils/Build/Products/Debug-iphoneos").absolutePath



    iosX64() {
        compilations.getByName("main") {
            val slicerUtils by cinterops.creating {
                defFile("SwiftSlicerUtils.def")
                compilerOpts(
                    "-framework",
                    "SlicerUtils",
                    "-F$slicerUtilsBaseFrameworkDirX64/"
                ) //As framework

            }

        }

        binaries.all {
            // Linker options required to link to the framework.
            linkerOpts("-framework", "SlicerUtils", "-F${slicerUtilsBaseFrameworkDirX64}/")
        }
    }

    iosArm64() {
        compilations.getByName("main") {
            val slicerUtils by cinterops.creating {
                defFile("SwiftSlicerUtils.def")
                compilerOpts(
                    "-framework",
                    "SlicerUtils",
                    "-F$slicerUtilsBaseFrameworkDirArm64/"
                )//As framework

            }

        }

        binaries.all {
            // Linker options required to link to the framework.
            linkerOpts("-framework", "SlicerUtils", "-F${slicerUtilsBaseFrameworkDirArm64}/")
        }
    }
  
```

I don't think it is a problem with the cinterop definition in the build.gradle.kts file, because the paths are correct and the shared code module builds without errors.

May somebody give me a clue?

**Comment by SvyatoslavScherbina** [comment] 2020-11-20 08:08
Probably a duplicate of [KT-40975](https://youtrack.jetbrains.com/issue/KT-40975). Try switching the `kotlin.native.enableDependencyPropagation` value in your `gradle.properties` file.
In any case, please stop using GitHub issues of this repository for anything and prefer other ways of getting some help: https://github.com/JetBrains/kotlin-native/issues/4079

**Closed by SvyatoslavScherbina** 2020-11-20 08:08 UTC
