### ISSUE TITLE
cinterop fail when project path has special  character。

### ISSUE THREAD

**Issue by acc110789** [JetBrains/kotlin-native#3242] opened 2019-08-07 10:16 UTC
if project path contain the character "@"。
for example：
“/Users/me/Document/example_mpp@1”
if there is a mpp module under “/Users/me/Document/example_mpp@1” which use cinterop, then cinterop will fail。

**Comment by artdfel** [comment] 2019-08-07 11:50
Hello! Can you share additional info on your case? Something like steps to reproduce this behaviour.

**Comment by acc110789** [comment] 2019-08-08 05:25
> Hello! Can you share additional info on your case? Something like steps to reproduce this behaviour.

reproduce steps:

**Comment by acc110789** [comment] 2019-08-08 05:30
![download](https://user-images.githubusercontent.com/11617214/62677371-aabf7e00-b9e0-11e9-9b22-46dd90656ee2.png)

**Comment by acc110789** [comment] 2019-08-08 05:32
first: We have a project with the name "TestInterop@1"
it contain the module 'mybaselib' and 'mylib'

**Comment by acc110789** [comment] 2019-08-08 05:32
![download-1](https://user-images.githubusercontent.com/11617214/62677460-fa05ae80-b9e0-11e9-8697-dd39ec0dcb91.png)

**Comment by acc110789** [comment] 2019-08-08 05:33
second: the 'mybaselib' is a simple mpp module . and the is only one class in its commonMain source set

**Comment by acc110789** [comment] 2019-08-08 05:34
![download-2](https://user-images.githubusercontent.com/11617214/62677517-2e796a80-b9e1-11e9-836c-1a6a06a37c3e.png)

**Comment by acc110789** [comment] 2019-08-08 05:37
third: let 'mylib' depend on 'mybaselib' ,  and this a .def file 'controller_bridge' in 'mylib' module 。 you don not need care about the content of 'controller_bridge.def' , just a normal object-c .def file

**Comment by acc110789** [comment] 2019-08-08 05:37
![download-3](https://user-images.githubusercontent.com/11617214/62677648-a778c200-b9e1-11e9-8b35-9c6aeb9be691.png)

**Comment by acc110789** [comment] 2019-08-08 05:38
forth: run './gradlew :mylib:cinteropController_bridgeIos'  and it fails.

**Comment by acc110789** [comment] 2019-08-08 05:40
please fix as quickly . we use jenkins to auto packaging ， and jenkins will generate path which contain the character '@'。

**Comment by acc110789** [comment] 2019-08-08 05:43
my kotlin version is 1.3.40

**Comment by artdfel** [comment] 2019-08-08 08:08
Thanks for the details! 
If you need to deal with it ASAP, try to use a more recent release of the compiler(like some `-dev` one). As far as I know, we already made a fix, that got to be released in 1.3.50.

**Comment by SvyatoslavScherbina** [comment] 2019-08-08 11:30
You can find more details on trying 1.3.50 EAP here: https://discuss.kotlinlang.org/t/kotlin-1-3-50-early-access-preview/13525

**Comment by acc110789** [comment] 2019-10-17 07:33
I update to 1.3.50, the bug still exist
please fix it

**Comment by artdfel** [comment] 2019-10-25 11:28
Thank you for reopening, now we managed to figure out the reasons for such behavior. When the fix will be available, there will be an update in this thread.

**Comment by artdfel** [comment] 2020-10-06 15:08
Closing this issue in favor of [KT-42500](https://youtrack.jetbrains.com/issue/KT-42500), please see #4079 for the details.

**Closed by artdfel** 2020-10-06 15:08 UTC
