### ISSUE TITLE
Precondition failed: NSArray element failed to match the Swift Array Element type

### ISSUE THREAD

**Issue by webfrea-k** [JetBrains/kotlin-native#2959] opened 2019-05-10 13:14 UTC
Hi!

I have a interface, inheriting from another interface like this:

```
interface Book : BaseBook {
    val name: String
}

interface BaseBook {
    val id: Long
}
```
Function for loading books (iOS and Android):
```
Utils.sdk()?.booksController().getBooks(successCallback:{ [weak self] books in
             print(books[0].name) <--------Error occurs here
                return KotlinUnit()
            }, errorCallback: { [weak self] error in
                return KotlinUnit()
        })
```
Error:
```
Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FrameworkBook but found kobjcc0: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.2.63.12/swift/stdlib/public/core/ArrayBuffer.swift, line 346
2019-05-10 14:44:01.547868+0200 SRSDK Demo[9918:12973242] Precondition failed: NSArray element failed to match the Swift Array Element type
Expected FrameworkBook but found kobjcc0: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.2.63.12/swift/stdlib/public/core/ArrayBuffer.swift, line 346
```
If I change Book to data class, everything works as expected. Is there something wrong with the way I am handling interfaces and objects or might there be a bug in K/N?

P.S. If I debug the iOS app, I can see the objects in array (the size of the array is correct too), but instead of objects and their properties I get:
```
[0] = (kobjcc0 *) 0x6000020f0180
    KotlinBase
        NSObject
            isa = (Class) kobjcc0
```

**Comment by webfrea-k** [comment] 2019-05-13 07:17
Actually, it doesn't have to be interface inheriting from interface. Single interface is enough to reproduce the problem.

**Comment by SvyatoslavScherbina** [comment] 2019-05-13 16:54
Thanks, confirmed.
Looks much like duplicate of #2830.

**Closed** 2019-05-14 11:02 UTC
