### ISSUE TITLE
TypeCastException when using generics

### ISSUE THREAD

**Issue by pardom** [JetBrains/kotlin-native#2752] opened 2019-03-08 16:56 UTC
I'm encountering type errors when trying to call a Kotlin generic function from Swift.

```swift
dispose = Oolong().runtime(
    init: Counter().init,
    // Cannot convert value of type '(Counter.Msg, Counter.Model) -> KotlinPair' to expected argument type '(Any?, Any?) -> KotlinPair'
    update: Counter().update,
    // Cannot convert value of type '(Counter.Model, (Counter.Msg) -> KotlinUnit) -> Counter.Props' to expected argument type '(Any?, (Any?) -> KotlinUnit) -> Any?'
    view: Counter().view,
    // Cannot convert value of type '(Counter.Props) -> KotlinUnit' to expected argument type '(Any?) -> KotlinUnit'
    render: self.render,
    runtimeScope: GlobalScope(),
    effectContext: Dispatchers().default,
    renderContext: Dispatchers().default
)
```

To work around this, I introduced [this function](https://github.com/pardom/oolong/pull/16/files#diff-b6307a0524635d6d8940c58b27823806R47) in Kotlin:

```kotlin
object Counter {
    fun runtime(render: Render<Props>): Dispose {
        return Oolong.runtime(init, update, view, render)
    }
}
```

And now instead of compile-time errors, I'm getting run-time exceptions of `kotlin.TypeCastException`. Is this expected behavior? If so, how can I call this function correctly from K\N?

Reproducible example here: https://github.com/pardom/oolong/pull/16

**Comment by SvyatoslavScherbina** [comment] 2019-03-11 08:45
Could you post the stacktrace?

**Comment by pardom** [comment] 2019-03-11 17:38
I'm not sure how to see the stacktrace as I'm unfamiliar with iOS/Xcode. The error `kotlin.TypeCastException` was simply printed to the output in Xcode. You can see the error by running the Xcode project here: https://github.com/pardom/oolong/pull/16

**Comment by SvyatoslavScherbina** [comment] 2019-03-11 17:43
> The error kotlin.TypeCastException was simply printed to the output in Xcode

Does the output have any additional info below or above this message?

**Comment by pardom** [comment] 2019-03-11 21:23
No, it does not.

**Comment by SvyatoslavScherbina** [comment] 2019-03-14 07:21
This exception is not related to generics. The problem is caused by a bug in `kotlinx.coroutines`, similar to this one: https://github.com/Kotlin/kotlinx.coroutines/issues/920

**Comment by elizarov** [comment] 2019-03-15 07:28
Can you share what is the exception?

**Comment by pardom** [comment] 2019-03-15 17:27
The Xcode console prints `kotlin.TypeCastException` but the app does not crash. You can reproduce this behavior by running the Xcode project in https://github.com/pardom/oolong/pull/16.

**Comment by SvyatoslavScherbina** [comment] 2020-04-13 11:00
Closing as obsolete.

**Closed by SvyatoslavScherbina** 2020-04-13 11:00 UTC
