### ISSUE TITLE
Invalid Kotlin Code being generated when consuming cocoapod CocoaLumberjack

### ISSUE THREAD

**Issue by vanniktech** [JetBrains/kotlin-native#3828] opened 2020-02-06 08:32 UTC
Kotlin Version: 1.3.61

Setup:

```
cocoapods {
  pod("CocoaLumberjack") // https://github.com/CocoaLumberjack/CocoaLumberjack
}
```

And then when trying to compile from XCode 11.1 I'm getting:

> e: /Users/niklas/dev/multiplatform/build/classes/kotlin/ios/main/multiplatform-cinterop-CocoaLumberjack.klib-build/kotlin/cocoapods/CocoaLumberjack/CocoaLumberjack.kt: (1270, 50): This annotation is not applicable to target 'getter'

This is the failing line:

```kotlin
    val newLogFileName: String
        @ObjCMethod("newLogFileName", "@16@0:8") @CCall.ReturnsRetained external get
```

**Comment by artdfel** [comment] 2020-02-11 11:56
Hello, @vanniktech! Seems like this issue is a duplicate of #3336. Please subscribe to it, and let's close this one for now. Feel free to reopen if the problem will remain after the fix.

**Closed by artdfel** 2020-02-11 11:56 UTC
