### ISSUE TITLE
Several K/N release tags fail to build from source due to C++ compile error

### ISSUE THREAD

**Issue by serebit** [JetBrains/kotlin-native#4016] opened 2020-03-23 14:41 UTC
Here's the output that all versions tested give in Gradle when attempting to build: https://hastebin.com/utasolaqum.rb

This happens with the following Kotlin/Native tags:
`1.4.0-M1`
`v1.3.71`
`v1.3.70`

The `1.3.70` EAP tags used to have this issue, but now cannot be built at all due to missing plugin versions on the JetBrains servers.

These builds were performed on a Linux system running Solus 4.1.

**Comment by serebit** [comment] 2020-03-25 16:55
This is fixed by #4024.

**Comment by SvyatoslavScherbina** [comment] 2020-03-26 08:56
Nice work, thank you!

> These builds were performed on a Linux system running Solus 4.1.

Kotlin/Native build is supposed to be completely independent from compiler and SDK installed to the system, but apparently it isn't, I can confirm this. (Because of this, Kotlin/Native build is ok on our build agents, but fails on your system).

**Comment by SvyatoslavScherbina** [comment] 2020-03-26 08:58
The fix is merged.

**Closed by SvyatoslavScherbina** 2020-03-26 08:58 UTC
