### ISSUE TITLE
Passing constant strings without copying corrupts them

### ISSUE THREAD

**Issue by wooky** [JetBrains/kotlin-native#1014] opened 2017-11-06 05:19 UTC
Tested with the version of Kotlin Native that comes with the 0.3.4 Kotlin Native Gradle plugin.

I have two simple files in my project:

**ctest.def:**
```c
---

char *mine;

void store(const char* what)
{
    mine = what;
}

void store_copy(const char* what)
{
    mine = malloc(strlen(what) + 1);
    strcpy(mine, what);
}

char* give()
{
    return mine;
}
```

**ktest.kt:**
```kotlin
import ctest.*
import kotlinx.cinterop.toKString

fun main(args: Array<String>) {
    val hello = "Hello World!"
    store(hello)
    println(give()?.toKString())

    store_copy(hello)
    println(give()?.toKString())
}
```

When I run this, I get two lines as expected, but the first line gets corrupted, only the second line is correct. Furthermore, the first line is inconsistent. For instance, most times I get something like "P╔", but sometimes I get "P╔̀" or "P╔¼" or something similar.

Doing this in a C application would have both lines be correct, but that's not the case within Kotlin, which is why I believe this is a bug.

**Comment by msink** [comment] 2017-11-06 07:22
https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md#passing-user-data-to-callbacks

**Comment by wooky** [comment] 2017-11-06 15:25
None of the samples involving StableRef deal with strings, though, only with callbacks. If strings also need to be wrapped in a StableRef, then either the samples that pass strings to C functions are wrong or they do something undocumented to those strings (e.g. copying them).

**Comment by msink** [comment] 2017-11-06 16:07
Anything passed to C must be StableRef, if C wants to save that pointer and use it later.

**Comment by wooky** [comment] 2017-11-07 20:43
There has to be a better way of passing strings than allocating a string and immediately releasing it. There's no reason for a static string to get copied to the heap in the first place, just point it to the location in memory where it statically resides.

**Comment by msink** [comment] 2017-11-08 00:42
There's no static strings.

**Comment by msink** [comment] 2017-11-08 01:56
Well, probably you want something like this:
```konan.immutableBinaryBlobOf('H', 'e', 'l', 'l', 'o').asCPointer()```

**Comment by olonho** [comment] 2017-11-08 10:30
This is intended behavior, we do not expose Kotlin object to the C world, but only pass temporary copies. So closing as not a bug.

**Closed by olonho** 2017-11-08 10:30 UTC

**Comment by wooky** [comment] 2017-11-09 05:58
Forgive me for bringing this back up, but how would you allocate a more permanent copy of the string and pass it to a C function, especially since they accept a String, not a byte pointer?

**Comment by msink** [comment] 2017-11-09 06:02
So make they accept byte pointer:
`noStringConversion = store store_copy`
