### ISSUE TITLE
Not in vtable error

### ISSUE THREAD

**Issue by drofwarcs** [JetBrains/kotlin-native#2865] opened 2019-04-14 21:01 UTC
Similar to https://github.com/JetBrains/kotlin-native/issues/2864, my project fails to build after upgrading to Kotlin 1.3.30. I'm getting a different error and from the `linkDebugFrameworkIos` task . I would like to make a reproducible project, however this project is pretty big and the error I'm giving does not give any good indication on what part of my project could be causing the error, or even if the error is caused by something in my project. This was building in 1.3.21

```
 * Compiler version info: Konan: 1.2 / Kotlin: 1.3.30
 * Output kind: FRAMEWORK

e: java.lang.Error: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@7076c20c not in  vtable of org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl@4c0b3475
	at org.jetbrains.kotlin.backend.konan.descriptors.ClassVtablesBuilder.vtableIndex(ClassVtablesBuilder.kt:160)
	at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.vtableIndex(ObjCExportCodeGenerator.kt:863)
	at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.createTypeAdapter(ObjCExportCodeGenerator.kt:939)
	at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.access$createTypeAdapter(ObjCExportCodeGenerator.kt:1)
	at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGenerator.emitRtti$backend_native_compiler(ObjCExportCodeGenerator.kt:168)
	at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produce$backend_native_compiler(ObjCExport.kt:67)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:317)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:201)
	at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:201)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:258)
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt:134)
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:55)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:53)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
	atorg.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
	at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
	at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)


> Task :common:linkDebugFrameworkIos FAILED
```

**Comment by homuroll** [comment] 2019-04-15 09:48
Will be helpful if you give us a reproducer for the bug.

**Comment by drofwarcs** [comment] 2019-04-17 14:14
@homuroll, I was able to drill down to the issue. When using an ios target, the compiler will fail if an enum class implements an interface. The compiler was fine building when targeting macOS however. Not sure if any of the other native targets are affected also. Added a reproducible project for you to test.

[Reproduce.zip](https://github.com/JetBrains/kotlin-native/files/3090042/Reproduce.zip)

**Comment by homuroll** [comment] 2019-04-19 09:53
Will be fixed in the upcoming 1.3.31 release.

**Closed by homuroll** 2019-04-19 09:53 UTC

**Comment by Thomas-Vos** [comment] 2019-04-23 10:40
I'm getting the same error. Thanks for the quick fix! Is there a workaround (apart from removing the interface) I could use so I can compile my project?

**Comment by SvyatoslavScherbina** [comment] 2019-04-23 10:56
Yes, you can make `override` method in a enum `final`, e.g.
```
enum class FooEnum : IFoo{
    FAKEFOO, FAKEBAR;

    final override fun canDoBbar(theBar: Any): Boolean { ... }
}
```

**Comment by WorldIsM** [comment] 2019-04-30 08:32
I have same issue, but I do not have any enums with interfaces. I have quite big project. Any suggestions how can I trace this error to specific class?

**Comment by SvyatoslavScherbina** [comment] 2019-04-30 08:33
@WorldIsM Try 1.3.31.

**Comment by WorldIsM** [comment] 2019-04-30 08:35
Do not help.

**Comment by SvyatoslavScherbina** [comment] 2019-04-30 08:36
Could you share your stacktrace?

**Comment by WorldIsM** [comment] 2019-04-30 08:41
`
11:22:47.380 [ERROR] [system.err] e: Compilation failed: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@592ef868 not in vtable of org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl@10650eb3
11:22:47.381 [ERROR] [system.err] 
11:22:47.382 [ERROR] [system.err]  * Source files: <List of my sweet kt files>
11:22:47.383 [ERROR] [system.err]  * Compiler version info: Konan: 1.2.1 / Kotlin: 1.3.31
11:22:47.383 [ERROR] [system.err]  * Output kind: FRAMEWORK
11:22:47.383 [ERROR] [system.err] 
11:22:47.383 [ERROR] [system.err] e: java.lang.Error: org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl@592ef868 not in vtable of org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl@10650eb3
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.descriptors.ClassVtablesBuilder.vtableIndex(ClassVtablesBuilder.kt:160)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.FunctionGenerationContext.lookupVirtualImpl(CodeGenerator.kt:656)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt$generateObjCImp$1.invoke(ObjCExportCodeGenerator.kt:528)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt$generateObjCImp$1.invoke(ObjCExportCodeGenerator.kt)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.generateObjCImp(ObjCExportCodeGenerator.kt:615)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.generateObjCImp(ObjCExportCodeGenerator.kt:524)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.createMethodVirtualAdapter(ObjCExportCodeGenerator.kt:821)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.createTypeAdapter(ObjCExportCodeGenerator.kt:967)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGeneratorKt.access$createTypeAdapter(ObjCExportCodeGenerator.kt:1)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.objcexport.ObjCExportCodeGenerator.emitRtti$backend_native_compiler(ObjCExportCodeGenerator.kt:169)
11:22:47.383 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.objcexport.ObjCExport.produce$backend_native_compiler(ObjCExport.kt:67)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:317)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:201)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.CodeGeneratorVisitor.visitModuleFragment(IrToBitcode.kt:201)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:42)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoidKt.acceptVoid(IrElementVisitorVoid.kt:258)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt:134)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$codegenPhase$1.invoke(BitcodePhases.kt)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:55)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:53)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
11:22:47.384 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
11:22:47.385 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:15)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
11:22:47.386 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
11:22:47.387 [ERROR] [system.err]       at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)
11:22:47.387 [ERROR] [system.err] 
11:22:47.566 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:22:47.566 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:22:47.566 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':linkMyDebugFrameworkIosArm64'.
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
11:22:47.567 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:22:47.568 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
11:22:47.568 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
11:22:47.568 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1m 22s
`

**Comment by SvyatoslavScherbina** [comment] 2019-05-06 08:28
May be related to #2938.

**Comment by alshan** [comment] 2019-09-11 22:27
The issue is still present in 1.3.50
It seems that `IrFunctionImpl@6e8a37b2 not in vtable...` error occurs in the case when `enum class` implements `interface` containing both - `properties` and `methods`.
If `enum class` implements `interface` containing only `properties` the error doesn't seem to occur.

**Comment by SvyatoslavScherbina** [comment] 2019-09-12 06:16
@alshan could you share your stack trace and/or provide a reproducer?

**Comment by SvyatoslavScherbina** [comment] 2019-09-13 07:44
@olonho 
```kotlin
interface Foo {
    fun foo()
}

enum class Bar : Foo {
    ZERO
    ;
    override fun foo() {}
}
```

**Comment by olonho** [comment] 2019-09-13 11:10
https://github.com/JetBrains/kotlin-native/pull/3339 shall help.

**Comment by alshan** [comment] 2019-09-13 15:18
> Which version of K/N do you use?
Konan: 1.3.50 / Kotlin: 1.3.50
