### ISSUE TITLE
Unable to download the compiler

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/kotlin-native#678] opened 2017-06-19 14:43 UTC
I am using the konan plugin (version 0.3) on Mac and I get an error:

```
16:40:07.001 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':downloadKonanCompiler' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
16:40:07.001 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':downloadKonanCompiler'.
16:40:07.001 [INFO] [org.gradle.api.Task] Downloading Kotlin Native compiler from http://download.jetbrains.com/kotlin/native/kotlin-native-macos-0.3 into /Users/federico/.konan
16:40:07.002 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
16:40:07.002 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':downloadKonanCompiler'
16:40:07.002 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :downloadKonanCompiler FAILED
16:40:07.002 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :downloadKonanCompiler (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.001 secs.
16:40:07.002 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.1 completed (0 in use)
16:40:07.002 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 4,5,main]] finished, busy: 0.001 secs, idle: 0.001 secs
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Cannot download Kotlin Native compiler
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.nio.channels.OverlappingFileLockException (no error message)
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:40:07.003 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
16:40:07.003 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
16:40:07.003 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
16:40:07.004 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
16:40:07.004 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 0.784 secs
````

It seems to try to download `http://download.jetbrains.com/kotlin/native/kotlin-native-macos-0.3`. I tried to download it in a browser and saw this:
![screen shot 2017-06-19 at 16 42 59](https://user-images.githubusercontent.com/439078/27290754-7311458a-550e-11e7-8ccd-abd171a14eab.png)

**Comment by olonho** [comment] 2017-06-19 15:05
Plugin with version 0.3 wasn't  published yet. Please use released version 0.2 or wait few days for release of 0.3 plugin.

**Comment by ftomassetti** [comment] 2017-06-19 15:09
I also tried specifying version 2. I get a different error but it does not work either:

```
17:06:57.328 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':downloadKonanCompiler'.
17:06:57.329 [INFO] [org.gradle.api.Task] Downloading Kotlin Native compiler from http://download.jetbrains.com/kotlin/native/kotlin-native-macos-0.2 into /Users/federico/.konan
17:06:57.329 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
17:06:57.329 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':downloadKonanCompiler'
17:06:57.329 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :downloadKonanCompiler FAILED
17:06:57.329 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :downloadKonanCompiler (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.002 secs.
17:06:57.329 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.1 completed (0 in use)
17:06:57.329 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 6,5,main]] finished, busy: 0.002 secs, idle: 0.0 secs
17:06:57.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:06:57.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:06:57.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:06:57.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:06:57.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Cannot download Kotlin Native compiler
17:06:57.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.nio.channels.OverlappingFileLockException (no error message)
17:06:57.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:06:57.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:06:57.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
17:06:57.331 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
17:06:57.331 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
17:06:57.331 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
```
Also trying to download it from the browser I get an error:
![screen shot 2017-06-19 at 17 07 58](https://user-images.githubusercontent.com/439078/27291899-e9522e64-5511-11e7-8cdf-c4447163c0e1.png)

Also, version 0.3 is the version suggested in https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md

**Comment by ilmat192** [comment] 2017-06-20 12:44
The 0.3 Gradle plugin is published and the compiler will be ready soon. But it looks like your issue relates to our dependency downloading and I'm going to investigate it.

**Comment by ilmat192** [comment] 2017-06-21 12:03
A fix for the issue is ready (but is not merged into master yet). As a workaround you may remove `$HOME/.konan/cache/.lock` and try to rerun your build using Gradle plugin v0.2 and Kotlin/Native compiler v0.2.

**Comment by JeffBNimble** [comment] 2017-06-21 15:03
I'm not sure if this is related or not or whether I should open a new issue. If I type:
`kotlinc -list_targets`
from the command line in one of the macos-0.2 samples, I see
`iphone:
iphone_sim:
macbook:                      (default)`

If I then type:
`TARGET=iphone_sim ./build.sh`
from the command line in one of the samples, it attempts to download the libffi-3.2.1-2darwin-ios-sim, but fails with the following:

`Downloading native dependencies (LLVM, sysroot etc). This is a one-time action performed only on the first run of the compiler.
Download dependency: http://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz (0 bytes/-). Done.
Exception in thread "main" java.lang.IllegalStateException: Cannot download dependencies.
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.maybeExecuteHelper(main.kt:174)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.downloadDependencies(main.kt:284)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processLib(main.kt:311)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.main(main.kt:35)
Caused by: java.lang.RuntimeException: Cannot download dependency: http://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz
	at org.jetbrains.kotlin.konan.DependencyDownloader.download(DependencyDownloader.kt:152)
	at org.jetbrains.kotlin.konan.DependencyDownloader.processDependency(DependencyDownloader.kt:80)
	at org.jetbrains.kotlin.konan.DependencyDownloader.run(DependencyDownloader.kt:164)
	at org.jetbrains.kotlin.konan.Helper0.run(Helper0.kt:31)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.maybeExecuteHelper(main.kt:170)
	... 3 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://download-cf.jetbrains.com/kotlin/native/libffi-3.2.1-2-darwin-ios-sim.tar.gz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.URL.openStream(URL.java:1045)
	at org.jetbrains.kotlin.konan.DependencyDownloader$download$1.invoke(DependencyDownloader.kt:127)
	at org.jetbrains.kotlin.konan.DependencyDownloader$download$1.invoke(DependencyDownloader.kt:27)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

I'm getting a 403 error (not authorized)

If I run the same command, except specify `TARGET=iphone` or `TARGET=macbook`, it works.

**Closed** 2017-06-24 07:20 UTC

**Comment by ilmat192** [comment] 2017-06-26 09:45
Merged: https://github.com/JetBrains/kotlin-native/pull/688/commits/b7e868a13e1a096bc85e49ebb28fec55acb0c50e
