### ISSUE TITLE
Using gradle composite builds causes duplicate symbols issue when linking

### ISSUE THREAD

**Issue by raniejade** [JetBrains/kotlin-native#3834] opened 2020-02-06 13:55 UTC
The project in question is https://github.com/raniejade/godot-kotlin/tree/raniejade/gh-workflows. The `samples:rotating-cube` project includes the `core` project (via gradle's includeBuild). Whenever I build the samples project I get the following error:

```
Produced library API in librotating_cube_api.h
error: Linking globals named 'knifunptr_gdnative0_godot_color_new_rgba': symbol multiply defined!
```

This does not happen when `samples:rotating-cube` is a sibling project of `core`.

I did some digging and here are my findings so far:

The `core` project declares a cinterop so it produces two klibs, this looks normal, however when I looked at the generated klib for `samples:rotating-cube` I see something weird, the cinterop klib is declared twice in its manifest.

```
unique_name=rotating-cube
compiler_version=1.3.61-release-13550
depends=stdlib posix core-cinterop-gdnative linux core core-cinterop-gdnative
abi_version=17
```

`core-cinterop-gdnative` is the klib produced from cinterop. Based on this finding, I tried making the dependency of `samples:rotating-cube` to `core` non-transitive by:

```
implementation(<...>) {
  isTransitive = false
}
```

After the change, the build passed. I've checked the generated klib for `samples:rotating-cube`:

```
unique_name=rotating-cube
compiler_version=1.3.61-release-13550
depends=stdlib posix linux core core-cinterop-gdnative
abi_version=17
```

Note that `core-cinterop-gdnative` is only declared only once now.

**Comment by ilmat192** [comment] 2020-02-07 13:10
Hello @raniejade! I've got a 404 error when trying to open the link you provided. Is the project public?

**Comment by raniejade** [comment] 2020-02-07 14:04
@ilmat192 sorry I merged the branch already (using the workaround I mentioned). The master branch has the same structure as the one I linked: https://github.com/raniejade/godot-kotlin

**Comment by raniejade** [comment] 2020-02-13 09:54
@ilmat192 any news on this?

**Comment by raniejade** [comment] 2020-02-13 11:21
I think I know what the problem is.

Say you have a project `core` and it declares a `linux` target with a cinterop `gdnative`. `core` will produce two artifacts `core.klib` and `cinterop-gdnative.klib`, where the former depends on the latter (you can see this in the klib's manifest).

Say you have another project `sample` that depends on `core`. `sample` declares a `linux` target as well. The compile task of `sample:linux` will depend on the two klibs produced `core`. So the problem here is that the compile task does not de-dupe the dependencies. `sample.klib`'s manifest will contain:

```
dependency= ... core.klib gdnative.klib gdnative.klib
```

`core.klib gdnative.klib` comes from `core.klib` and it's dependencies
` gdnative.klib` comes from `gdnative.klib`.

The linking phase will fail because it sees duplicate symbols from `gdnative.klib`.

With that said, I'm not sure why setting `isTransitive` to `false` fixes the problem.

**Comment by raniejade** [comment] 2020-02-23 04:35
@ilmat192 Any updates?

**Comment by ilmat192** [comment] 2020-02-26 11:44
Hi @raniejade ! Sorry for the delay with the answer.

In 1.3.70, the compiler will be more tolerate to duplicated libraries and you'll only get a warning. You already can use the EAP-3 version, just specify `1.3.70-eap-274` as a Gradle plugin version.

But the root cause of this problem doesn't relate to the compiler. The problem is caused by the way the Gradle plugin handles cinterop klibs. I've created a YT issue to track this: https://youtrack.jetbrains.com/issue/KT-37051.

**Comment by SvyatoslavScherbina** [comment] 2020-09-29 10:15
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-37051

**Closed by SvyatoslavScherbina** 2020-09-29 10:15 UTC
