### ISSUE TITLE
Environment Variable Support For Def Files

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#3631] opened 2019-12-02 02:37 UTC
With the **def** file format it doesn't support the use of environment variables. If environment variables were supported then a **def** file would look like this:

```
linkerOpts = -L${HOME}/ncurses-6.1/lib -lncurses
compilerOpts = -I${HOME}/ncurses-6.1/include
headers = curses.h
package = ncurses
```

The main use case for supporting environment variables in a **def** file is to allow custom built C libraries to be used without having to hard code paths in a **def** file, which is a big issue when using a VCS (eg Git).

**Comment by msink** [comment] 2019-12-02 09:29
Probably duplicate of #3484 and #2314

**Comment by artdfel** [comment] 2019-12-02 13:29
Why do you prefer to use `.def` configuration instead of setting these options by Gradle?

**Comment by napperley** [comment] 2019-12-10 21:27
Environment variables would be set by Gradle. In a def file the environment variables would be read only.

**Comment by SvyatoslavScherbina** [comment] 2021-04-05 11:54
> The main use case for supporting environment variables in a def file is to allow custom built C libraries to be used without having to hard code paths in a def file, which is a big issue when using a VCS (eg Git).

As mentioned above, you can easily pass anything from Gradle. See [the documentation](https://kotlinlang.org/docs/mpp-dsl-reference.html#cinterops) for more details.
I'm closing this issue, because we are  [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079). Feel free to submit it again to https://kotl.in/issue if it still affects you.

**Closed by SvyatoslavScherbina** 2021-04-05 11:54 UTC
Labels: enhancement
