### ISSUE TITLE
Memory.cpp:1091: runtime assert: Must be positive

### ISSUE THREAD

**Issue by sspogra** [JetBrains/kotlin-native#3776] opened 2020-01-23 05:33 UTC
swift ios App was crashed when trying to parse json string.
Json.parse(ArrayListSerializer(), filesString)

kfun:kotlin.text.substring@kotlin.CharSequence.(kotlin.Int;kotlin.Int)kotlin.String + 96 at Strings.kt:1262

**Comment by artdfel** [comment] 2020-01-23 08:07
Hello @sspogra! Can you share the project or some steps to reproduce the issue or a full stack trace maybe? Also, what version of the Kotlin compiler you're using here? There was a similar issue a few time ago, see [here](https://github.com/JetBrains/kotlin-native/issues/3259).

**Comment by sspogra** [comment] 2020-01-23 10:26
Hello @artdfel  I am using kotlin plugin version 1.3.61 and studio 3.6-1, gradle_version = '3.5.3'

This crash is not happened every time Its happened 2 times in a try of 10 times  and also crashed on different different case:-

1.  Parse DocumentSnapshot.getString("some_key") 

actual fun DocumentSnapshot.getString(field: String): String? {
    val value = valueForField(field) // app Crashed here
    return if(value !=null){
        if(value is String){
            value
        }else{
            value.toString()
        }
    }else{
        null
    }
}
![image](https://user-images.githubusercontent.com/49437548/72972977-5f642500-3df2-11ea-80c4-675f557bf609.png)

2. Json.parse(KSerializer<PolicyAttachment>.list, filesString)

![image](https://user-images.githubusercontent.com/49437548/72976532-ca185f00-3df8-11ea-94ab-b5d04676d829.png)

**Comment by artdfel** [comment] 2020-01-23 13:24
Thanks! At first sight, I cannot tell anything about the root cause, but it may be a compiler bug. Please try to minimize the project and share it in any way, that is suitable for you.

**Comment by serebit** [comment] 2020-03-18 21:16
I'm experiencing the same issue with a Linux x64 project, and can reproduce it consistently, although it's at a different place in `Memory.cpp` (line 1135). Tag 0.5.2 of https://github.com/serebit/wraith-master can replicate the issue by clicking on the `Reset` button 25 times.

**Comment by SvyatoslavScherbina** [comment] 2020-08-13 15:01
Closing as incomplete. Feel free to reopen with a reproducer.

**Closed by SvyatoslavScherbina** 2020-08-13 15:01 UTC
