### ISSUE TITLE
Executables Generated By Konan Aren't Statically Linked

### ISSUE THREAD

**Issue by napperley** [JetBrains/kotlin-native#469] opened 2017-04-11 00:46 UTC
Every Linux/ARM executable generated by **konanc** is dynamically linked. Shouldn't the executables be statically linked?

Ran the following command on a generated executable, **file TetrisRaspberry.kexe**. Below is the output:

```
TetrisRaspberry.kexe: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=f7f67296e36d83a6660722c60f1c86eceb2ee3c8, not stripped
```

**Comment by olonho** [comment] 2017-04-11 05:07
It depends on how do you link final binary (see linker commands in https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/LinkStage.kt#L141). For Linux we dynamically link with libc, as static linking would be waste of space.
For embedded targets you need to compile diffeently.

**Comment by napperley** [comment] 2017-04-11 05:31
Almost forgot, it is very common for native Linux desktop and server
programs to be dynamically linked. On Debian based systems (includes Linux
Mint and Ubuntu) dynamic linking is the standard way to generate
executables.

**Comment by napperley** [comment] 2017-04-11 05:32
I take it Kotlin Native doesn't have a standard way to do deployment?

**Comment by napperley** [comment] 2017-04-12 07:58
Running **ldd TetrisRaspberry.kexe** provides a different result:

```
not a dynamic executable
```

**Comment by napperley** [comment] 2017-04-12 21:25
Is additional documentation going to be provided on the Kotlin Native linking process?

**Comment by olonho** [comment] 2017-04-14 04:26
What part of Kotlin/Native linking process you're interested in? Linking process is similar to that of C/C++ programs.

**Comment by napperley** [comment] 2017-04-14 05:33
Based on the BBB experience (**Tetris** sample) with a generated Linux executable the Kotlin Native runtime is statically linked, all other external C libraries (eg SDL) and assets (eg image files) that are used are dynamically linked.

**Comment by olonho** [comment] 2017-04-18 06:42
For linking downloaded toolchain is used. We decided to link dynamically only C library, which is known to be present everywhere, and C++ library on Mac, everything else is linked statically. This could be tweaked by modifying how linker is invoked in https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/LinkStage.kt#L119

**Comment by napperley** [comment] 2017-04-18 20:52
@olonho - In your link there is a [TODO](https://github.com/JetBrains/kotlin-native/blob/master/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/LinkStage.kt#L120) mentioning a properties file. Are there any plans to allow the linker to be tweaked using a properties file instead of via the terminal (using **-linkerArgs**)?

**Comment by olonho** [comment] 2017-04-18 21:16
Note that property file is konan.properties, not per-library .def file. And there only common for all platform binaries may be present.

**Comment by olonho** [comment] 2017-04-20 20:20
I will close this bug with 'works as intended'. Any objections?

**Closed by olonho** 2017-04-20 20:20 UTC
