### ISSUE TITLE
"Must be newly frozen" exception while freezing object in constructor

### ISSUE THREAD

**Issue by skvav** [JetBrains/kotlin-native#3759] opened 2020-01-15 15:02 UTC
I encountered a new type of exception after update to Kotlin/Native 1.5.61: "/Users/teamcity3/buildAgent/work/4d622a065c544371/runtime/src/main/cpp/Memory.cpp:2441: runtime assert: Must be newly frozen"
Crash appears in the following code:
```Kotlin
package ru.zenmoney.mobile.platform

import platform.Foundation.*
import kotlin.native.concurrent.*
import kotlinx.serialization.Serializable

@Serializable(with = DateSerializer::class)
actual class Date: Comparable<Date> {
    val date: NSDate

    constructor(date: NSDate) {
        this.date = date
        freeze() // <- HERE exception is thrown
    }
```
Could you explain please, is it forbidden to call freeze() inside object constructor for some reason or it is a bug of compiler?

**Comment by artdfel** [comment] 2020-01-16 08:40
Hello! Can you please extend the report with a more complete piece of code? For now, I cannot reproduce the crash locally.

**Comment by olonho** [comment] 2020-01-20 13:52
It is possible to call freeze() in constructor, looks like a problem in runtime/compiler, so we need reproducer to fix the problem.

**Comment by SvyatoslavScherbina** [comment] 2020-08-13 15:02
Closing as incomplete. Feel free to reopen with a reproducer.

**Closed by SvyatoslavScherbina** 2020-08-13 15:02 UTC
