### ISSUE TITLE
setUnhandledExceptionHook not called from another thread (reverse c interop)

### ISSUE THREAD

**Issue by josephdwyer** [JetBrains/kotlin-native#3542] opened 2019-11-04 23:45 UTC
This example demonstrates the setUnhandledExceptionHook not being called from a callback on another thread. Unfortunately, the code is a bit more complex than other issues I have filed. This is intended to reproduce a scenario where some work is started in the kotlin library for the app to perform, and the app will call a completion when finished. 

Compile the example:
```
kotlinc-native -g knlibrary.kt -produce dynamic -o knlibrary.dll
```

Using instructions from [here](https://kotlinlang.org/docs/tutorials/native/dynamic-libraries.html#compiling-and-running-the-example-on-windows) to consume the library.

Note: using the latest master build (kotlinc-native 1.3.70-dev-1244) there is no need to mess with the extra symbols in the names of stuff.
```
lib.exe /def:knlibrary.def /out:knlibrary.lib
cl.exe consumer.c knlibrary.lib
consumer.exe
```

Program output:
```
>consumer.exe
Calling test
Hello Kotlin/Native!
Calling startWork
Starting thread...
In doWork ... calling completion
In the callback, causing exception (param: 5)
```

Expected: setUnhandledExceptionHook callback logs the exception

consumer.c
```
#include <stdio.h>
#include "knlibrary_api.h"
#include <windows.h> 

// hold a handle for the work so we can wait before exiting the program
HANDLE workHandle;

// struct needed to pass both the function pointer and parameter to doWork
typedef struct s_call {
   void (*callback)();
   void *param;
} call;

DWORD WINAPI doWork( LPVOID lpParam ) 
{
   call c = *(call*)lpParam;

   // do some work in the app like networking etc
   // then call the callback
   printf("In doWork ... calling completion\n");
   c.callback(c.param);

   return 0;
}

void startWork(void (*callback)(), void *param) 
{ 
   DWORD threadId;
   // set up method parameter
   call c;
   c.callback = callback;
   c.param = param;

   printf("Starting thread...\n");

   HANDLE handle = CreateThread( 
         NULL,                   // default security attributes
         0,                      // use default stack size  
         doWork,                 // thread function name
         &c,                     // argument to thread function 
         0,                      // use default creation flags 
         &threadId);             // returns the thread identifier 

   if (handle == NULL) 
   {
      ExitProcess(3);
   }
   // store the handle
   workHandle = handle;

   return 0;
} 

int main()
{
   knlibrary_ExportedSymbols* lib = knlibrary_symbols();

   printf("Calling test\n");
   lib->kotlin.root.knlibrary.test(&startWork);

   // wait for the background work to complete
   WaitForSingleObject(workHandle, 10000);
   printf("Thread finished\n");
   CloseHandle(workHandle);

   printf("Test complete\n");

   return 0;
}
```

knlibrary.kt
```
package knlibrary

import kotlin.native.*
import kotlin.native.concurrent.*

import kotlinx.cinterop.CFunction
import kotlinx.cinterop.COpaquePointer
import kotlinx.cinterop.CPointer
import kotlinx.cinterop.StableRef
import kotlinx.cinterop.invoke
import kotlinx.cinterop.staticCFunction
import kotlinx.cinterop.asStableRef

typealias StartWorkImpl = CPointer<CFunction<(COpaquePointer, COpaquePointer) -> Unit>>

fun test(startWork: StartWorkImpl) {
    println("Hello Kotlin/Native!")

    // set up exception logging
    setUnhandledExceptionHook({
        throwable: Throwable -> OnUnhandledException(throwable)
    }.freeze())

    // pass a completion to startWork that will be called when the work is done
    // use a staticCFunction & StableRef to the callback since this is the pattern 
    // for callbacks that can capture variables.
    val someState = 5;
    val callback = makeCallback({ CausesError(someState) })
    println("Calling startWork")
    startWork(callback.completion, callback.parameter)
}

fun OnUnhandledException(t: Throwable) {
    println("EXCEPTION: ${t}")
    t.printStackTrace()
}

fun CausesError(param: Int) {
    println("In the callback, causing exception (param: $param)")
    val result = param / 0
    println("Shouldn't make it here")
}

fun makeCallback(completion: () -> Unit): CallbackWithCapture {
    completion.freeze()

    val completionRef = staticCFunction(fun(callbackPtr: COpaquePointer) {
        initRuntimeIfNeeded()

        val callbackRef = callbackPtr.asStableRef<() -> Unit>()
        val callback = callbackRef.get()
        callbackRef.dispose()
        callback()
    })

    val callbackStableRef: StableRef<() -> Unit> = StableRef.create(completion)
    callbackStableRef.freeze()

    return CallbackWithCapture(completionRef, callbackStableRef.asCPointer())
}

data class CallbackWithCapture(val completion: COpaquePointer, val parameter: COpaquePointer) {
    init {
        freeze()
    }
}
```

**Comment by josephdwyer** [comment] 2019-11-05 16:47
@olonho I was using an older version

kotlinc-native -version
```
info: kotlinc-native 1.3.40-dev-2423 (JRE 1.8.0_201-b09)
Kotlin/Native: 1.3-dev
```

but I updated to 1.3.70 and still have the same problem, but the build instructions are a bit better due to a previous fix.
```
info: kotlinc-native 1.3.70-dev-1244 (JRE 1.8.0_201-b09)
Kotlin/Native: 1.3.70-dev
```

**Comment by olonho** [comment] 2019-11-07 06:19
https://github.com/JetBrains/kotlin-native/pull/3554 sketches possible solution.

**Comment by benasher44** [comment] 2020-04-21 15:06
@olonho is there any possibility of seeing a fix for this in 1.4? This is our main blocker on Windows unfortunately

**Comment by benasher44** [comment] 2020-04-21 15:06
Would you like us to create a matching KT ticket?

**Comment by benasher44** [comment] 2020-04-21 21:09
@SvyatoslavScherbina is there any possibility of seeing a fix for this in 1.4? This is our main blocker on Windows unfortunately

**Comment by SvyatoslavScherbina** [comment] 2020-04-22 08:22
> Would you like us to create a matching KT ticket?

No.

> is there any possibility of seeing a fix for this in 1.4?

I can't promise you that.

> This is our main blocker on Windows unfortunately

I see. I'll check what we can do.

Does wrapping `staticCFunction` body to `try-catch` help? E.g.
```kotlin
val completionRef = staticCFunction(fun(callbackPtr: COpaquePointer) {
    initRuntimeIfNeeded()
    try {
        val callbackRef = callbackPtr.asStableRef<() -> Unit>()
        val callback = callbackRef.get()
        callbackRef.dispose()
        callback()
    } catch (e: Exception) {
        // Report and terminate.
    }
})
```

If yes, is it a suitable workaround for you?

**Comment by benasher44** [comment] 2020-04-22 16:04
We can do that, but the problem is the scalability of that solution. We have to be careful that any time we go from windows to K/N we wrap all code in an exception handler, if we're not on the main thread.

Maybe there is some way to ship #3554 behind a gradle flag or something? Not sure if that's actually possible — just putting ideas out.

**Comment by SvyatoslavScherbina** [comment] 2020-04-22 16:26
> the problem is the scalability of that solution. We have to be careful that any time we go from windows to K/N we wrap all code in an exception handler, if we're not on the main thread.

What I'm trying to say is that wrapping `staticCFunction` bodies is probably enough. So I have to repeat my question:

> Does wrapping staticCFunction body to try-catch help?

Can you confirm that it fixes the issue? Can you confirm that wrapping regular function throwing exception is not necessary?
Is wrapping `staticCFunction` bodies still not scalable for your case?

> Maybe there is some way to ship #3554 behind a gradle flag or something? Not sure if that's actually possible — just putting ideas out.

https://github.com/JetBrains/kotlin-native/pull/3554 is not correct at the moment.

**Comment by benasher44** [comment] 2020-04-22 16:42
Oh I see. We'll give that a try and get back to you. Thanks for your help!

**Closed** 2021-07-30 15:38 UTC
