### ISSUE TITLE
Symbol multiply defined due to global_ctors

### ISSUE THREAD

**Issue by Tobi29** [JetBrains/kotlin-native#1294] opened 2018-02-08 13:08 UTC
The naming mechanism with `llvm.global_ctors` has a chance of colliding whenever one uses the same filenames accross different packages (which works fine on JVM and JS of course), which is especially annoying when you collide with a file in the standard library (e.g. `Numbers.kt`).

Is there any reason those cannot use package prefixes like everything else?

If one creates ~28 files (making their name appear alphabetically before `Numbers.kt` seems to be needed when using a single directory) containing something like:
```
private val a = run {
    println("a")
    Unit
}
```
And a file called `Numbers.kt` with the same contents as the other ones.
Then using a compilation command like:
```
konanc A1.kt A2.kt A3.kt A4.kt A5.kt A6.kt A7.kt A8.kt A9.kt A10.kt A11.kt A12.kt A13.kt A14.kt A15.kt A16.kt A17.kt A18.kt A19.kt A20.kt A21.kt A22.kt A23.kt A24.kt A25.kt A26.kt A27.kt A28.kt Numbers.kt Print.kt
```
Compiling that is enough to cause a collision. (It might not be exactly 28 depending on how exactly the standard library was compiled)

Yes I managed to trip this accidentally...

**Comment by olonho** [comment] 2018-02-08 13:50
Could you please provide gist/tarball with files which reproduces the issue. Also exact build error would be nice to see.

**Comment by Tobi29** [comment] 2018-02-08 14:55
Created a basic build (just two konan invocations in a bash script) that first creates a library using a package `a` and then a program using package `b` and a main function that accesses a property in the two packages.
[konan-bug.tar.gz](https://github.com/JetBrains/kotlin-native/files/1707517/konan-bug.tar.gz)


The library is created fine, but the program compilation fails due to the conflict described above.

As I mentioned the issue can be triggered by forcing a similar scenario with the standard library (instead of a custom one like here).

Error from compiling:
```
llvm-lto: error: Linking globals named 'Numbers_init_0': symbol multiply defined!
error: compilation failed: The /home/tobias/.konan/dependencies/clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto command returned non-zero exit code: 1.

 * Source files: Main.kt, Numbers.kt
 * Compiler version info: Konan: EAP 0.6.0.0 / Kotlin: 1.2.0
 * Output kind: PROGRAM

exception: org.jetbrains.kotlin.konan.KonanExternalToolFailure: The /home/tobias/.konan/dependencies/clang-llvm-5.0.0-linux-x86-64/bin/llvm-lto command returned non-zero exit code: 1.
        at org.jetbrains.kotlin.konan.exec.Command.handleExitCode(ExecuteCommand.kt:96)
        at org.jetbrains.kotlin.konan.exec.Command.execute(ExecuteCommand.kt:66)
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:50)
        at org.jetbrains.kotlin.backend.konan.LinkStage.runTool(LinkStage.kt:46)
        at org.jetbrains.kotlin.backend.konan.LinkStage.llvmLto(LinkStage.kt:65)
        at org.jetbrains.kotlin.backend.konan.LinkStage.access$llvmLto(LinkStage.kt:28)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:212)
        at org.jetbrains.kotlin.backend.konan.LinkStage$linkStage$1.invoke(LinkStage.kt:28)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.LinkStage.linkStage(LinkStage.kt:207)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt:106)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt$runTopLevelPhases$5.invoke(KonanDriver.kt)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:139)
        at org.jetbrains.kotlin.backend.konan.PhaseManager$phase$$inlined$with$lambda$1.invoke(KonanPhases.kt:118)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.PhaseManager.phase$backend_native_compiler(KonanPhases.kt:138)
        at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:105)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:61)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:39)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:108)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:183)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:174)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:34)
        at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:29)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:176)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:188)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:27)
```

**Comment by olonho** [comment] 2018-02-09 09:27
Thanks, we have a simple fix for your problem, but it doesn't work on all target platforms, so we have to redisign initialization somewhat to make work better.

**Comment by olonho** [comment] 2018-02-21 18:28
Shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1336

**Comment by olonho** [comment] 2018-02-26 20:26
Please try now, expected to work with current master.

**Comment by Tobi29** [comment] 2018-02-26 21:27
Well, trying with 049d29af75c382dc97c6947c5e8ab43d504cca40 (master) there is a clash again with `Numbers_0` (otherwise same error).

Trying with the pull request commits:
Compiling with 03e5802566edba7975fcff97b2506cda14132932 actually appears to work as expected (on x86_64 that is).
21e7a4298f857dcb3cf530123f34561fb204e017 breaks it again.

Basically, the problem appears as soon as any global symbol is named after a file name, without unique prefixes/suffixes. The counter suffix however is not unique accross modules (hence this issue is not possible in a single module).

I'm not exactly familiar with the specifics of LLVM IR, so I can't really tell how to approach this in a good way. (Other than making sure the symbols are "guaranteed" unique, e.g. by putting package or module names into them)

**Comment by olonho** [comment] 2018-02-27 05:40
Right, due to small typo, it wasn't fixed, https://github.com/JetBrains/kotlin-native/pull/1363 shall do.

**Comment by Tobi29** [comment] 2018-02-27 18:04
Well, that commit just reverts 21e7a4298f857dcb3cf530123f34561fb204e017, which breaks compilation on MIPS again (not just for this particular issue, but basically MIPS support is broken completely), so that does not seem like a good option. (It of works on x86_64 however at least)

So, using `LLVMExternalLinkage` breaks due to name collisions and `LLVMPrivateLinkage` breaks on MIPS due to LLVM reasons that I don't know of.

Looking at some documentation and output of `clang` a bit, those use `LLVMInternalLinkage` essentially for `static` functions in C and changing Kotlin/Native to use that for initializers seems to work (it compiles fine, including MIPS support) and executes x86_64 fine. I cannot actually run the MIPS binaries easily, so no idea if they actually do what they are supposed to.

**Comment by olonho** [comment] 2018-03-01 07:16
It was a MIPS issue, which I resolved using anonymous non-static function in 1363, now MIPS still works and ctors problem goes away.

**Comment by Tobi29** [comment] 2018-03-01 09:50
Seems to be working as expected on my end as well.

**Closed** 2018-03-01 13:19 UTC
