### ISSUE TITLE
Companion Object property change from Swift gives ThrowInvalidMutabilityException at Internal.kt

### ISSUE THREAD

**Issue by Syrou** [JetBrains/kotlin-native#2225] opened 2018-10-17 13:32 UTC
This kotlin-native code:
```
class MahSingleton {
    companion object {
       var randomText:String
       fun setKex(text:String){
            randomText = text
        }
    }
}
```

Exporting this code as a iOS Framework and running this:

```
var singleton: MahSingleton.Companion = MahSingleton.Companion.init()
singleton.setKex(text: "WHAT")
```
(FYI: Same with running MahSingleton.Companion() instead of using .init() )

Gives 
```
kfun:kotlin.native.concurrent.InvalidMutabilityException.<init>(kotlin.String)kotlin.native.concurrent.InvalidMutabilityException at Freezing.kt
```

While working just fine if you try to run the same code from Android. Why does it crash on iOS?

Running version '0.9.2' of kotlin-native

**Comment by olonho** [comment] 2018-10-17 14:32
This is intended behavior. Singleton objects, including companions are not mutable, see https://github.com/JetBrains/kotlin-native/blob/master/IMMUTABILITY.md. You could mark your companion as `@ThreadLocal`, although.

**Comment by Syrou** [comment] 2018-10-17 14:57
@olonho What dependency is required? It does not seem to be included in stdlib

**Comment by olonho** [comment] 2018-10-17 16:00
No dependencies, it is in stdlib. See - https://github.com/JetBrains/kotlin-native/blob/70e6b711349cf3a5bd937b6fcec124d2ca1244ef/runtime/src/main/kotlin/kotlin/native/Annotations.kt#L49 for declaration and https://github.com/JetBrains/kotlin-native/blob/70e6b711349cf3a5bd937b6fcec124d2ca1244ef/samples/videoplayer/src/main/kotlin/DecoderWorker.kt#L23 for usage example.

**Comment by Syrou** [comment] 2018-10-18 07:02
@olonho Seems like this is not supported when you try to use it in the common doing multiplatform
I guess the 'correct' way would be to implement a expect/actual setup of it then?

**Comment by olonho** [comment] 2018-10-18 09:09
You can create expect typealias being `@ThreadLocal` on Native and nothing on JVM.

**Comment by Alex009** [comment] 2018-10-18 09:16
@olonho maybe add this expect/actual realization in stdlib? When use multiplatform with native it's really needed to mark mutability annotations in common code.
Or maybe create multiplatform-additions library with this declaration and other useful...

**Comment by Syrou** [comment] 2018-10-18 10:04
@Alex009 @olonho Agree 100% this is going to create a lot of issues down the line if its not easily supported from common code

**Comment by olonho** [comment] 2018-10-22 14:09
For now work as designed, so closing the original issue.

**Closed by olonho** 2018-10-22 14:09 UTC
