### ISSUE TITLE
NSMutableDictionary not convert to MutableMap.

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3065] opened 2019-06-13 08:18 UTC
Version: 1.2.1

OC:
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;

generated klib:
public final var extra: platform.Foundation.NSMutableDictionary /* compiled code */

expect:
public final var extra: kotlin.collections.MutableMap

**Comment by artdfel** [comment] 2019-06-13 09:01
I am not sure, why this behavior was expected. [Documentation](https://kotlinlang.org/docs/reference/native/objc_interop.html#collections) especially notes this case of `NSMutableDictionary` and `NSMutableSet` usage.

**Comment by DTHeaven** [comment] 2019-06-13 09:30
> I am not sure, why this behavior was expected. [Documentation](https://kotlinlang.org/docs/reference/native/objc_interop.html#collections) especially notes this case of `NSMutableDictionary` and `NSMutableSet` usage.

It's inconvenient in hybrid project, there's so much old code.
Why not to convert to map?

**Comment by artdfel** [comment] 2019-06-13 16:10
We agree, that the current situation can be improved. But for now, there is no obvious solution, due to some design differences between K/N and Objective-C. For now, I can only advise you to keep this in mind while using the NSMutableDictionary and to assure, that when we come to manage this(can't tell if it will be soon), we'll let you know.

**Comment by DTHeaven** [comment] 2019-06-14 06:24
> We agree, that the current situation can be improved. But for now, there is no obvious solution, due to some design differences between K/N and Objective-C. For now, I can only advise you to keep this in mind while using the NSMutableDictionary and to assure, that when we come to manage this(can't tell if it will be soon), we'll let you know.

Thank you.

**Comment by SvyatoslavScherbina** [comment] 2020-04-13 12:40
Closing as duplicate of https://youtrack.jetbrains.com/issue/KT-35253

**Closed by SvyatoslavScherbina** 2020-04-13 12:40 UTC
