### ISSUE TITLE
Compilation error with Xcode 11.4 for iOS with Kotlin Native MPP

### ISSUE THREAD

**Issue by kar** [JetBrains/kotlin-native#4035] opened 2020-03-27 10:20 UTC
After updating XCode it seems like compilation towards iOS fails. Here is the log:

```
$ ./gradlew packForXcode

> Configure project :common
Kotlin Multiplatform Projects are an experimental feature.

> Task :common:linkDebugFrameworkIos FAILED
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: library not found for -lSystem

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:linkDebugFrameworkIos'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
2 actionable tasks: 1 executed, 1 up-to-date
```

I'm here to provide more input as needed.

**Comment by artdfel** [comment] 2020-03-31 08:41
Hello, @kar! Which XCode and Kotlin/Native versions you're using here?

**Comment by kar** [comment] 2020-03-31 11:05
@artdfel Xcode 11.4 and KN 1.3.71

**Comment by artdfel** [comment] 2020-03-31 14:53
I cannot reproduce an error on my machine. Can you share the project? Or at least your `packForXcode` task definition.

**Comment by khoatd92** [comment] 2020-06-11 08:24
@kar Did you solve it?

**Comment by SvyatoslavScherbina** [comment] 2020-09-29 15:09
Got no reproducer, closing.

**Closed by SvyatoslavScherbina** 2020-09-29 15:09 UTC
