### ISSUE TITLE
Are there any way for modify Other Link Flag on Xcode by Gradle?

### ISSUE THREAD

**Issue by ImanX** [JetBrains/kotlin-native#4141] opened 2020-04-27 14:24 UTC
I built a library in `Kotlin//Native` and I'll modify Other Link Flag when integrating lib on Xcode by `Gradle` , Are there any way for change of Other Link Flag? I use `cocoapods`

https://youtrack.jetbrains.com/issue/KT-38611?project=kt
More details: https://github.com/JetBrains/kotlin-native/issues/4079

**Comment by SvyatoslavScherbina** [comment] 2020-05-08 12:38
Closing as duplicate of [KT-38611](https://youtrack.jetbrains.com/issue/KT-38611).

**Closed by SvyatoslavScherbina** 2020-05-08 12:38 UTC
